# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 680d75deda20d0d4d1542ead80fa4cacebab50390577d1a9c497f7b16368a287c76ad97bb2c87efc5a16d9e6e96cc204975d0324cea081546683204a0f3b5ac2

test:
  secret_key_base: 7f75a9299c660ab30205a0407ca258c8c7761929a5312eaaad5023a5e1491df485075a1b337ca6a1896f358edb01817a86a548e7ad7c0282e5db2ac71b5c4401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
